project_id = "invdjkxkyytdpervudzw"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.rewrite-article]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.admin-users]
verify_jwt = false
