// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-articles.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.80.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-articles.ts
var list_articles_default = defineTool({
  name: "list_articles",
  title: "List articles",
  description: "List articles visible to the signed-in user, newest first. Optional text search and status filter.",
  inputSchema: {
    query: z.string().trim().optional().describe("Free-text search across English and Persian titles."),
    status: z.enum(["draft", "published"]).optional().describe("Filter by article status."),
    limit: z.number().int().min(1).max(50).optional().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ query, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("articles").select("id, slug, title_en, title_fa, summary_en, summary_fa, status, tags, categories, published_at, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) q = q.eq("status", status);
    if (query) q = q.or(`title_en.ilike.%${query}%,title_fa.ilike.%${query}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { articles: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-article.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_article_default = defineTool2({
  name: "get_article",
  title: "Get article with slides",
  description: "Fetch one article by slug, including its ordered slides (bilingual title and body).",
  inputSchema: { slug: z2.string().trim().min(1).describe("Article slug, e.g. 'my-article'.") },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: article, error } = await supabase.from("articles").select("id, slug, title_en, title_fa, summary_en, summary_fa, status, tags, categories, cover_url, published_at").eq("slug", slug).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!article) throw new ToolError(`No article found with slug "${slug}"`);
    const { data: slides, error: slidesError } = await supabase.from("slides").select("order_num, title_en, title_fa, body_en, body_fa, media_urls").eq("article_id", article.id).order("order_num", { ascending: true });
    if (slidesError) return { content: [{ type: "text", text: slidesError.message }], isError: true };
    const payload = { article, slides: slides ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/create-article-draft.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var create_article_draft_default = defineTool3({
  name: "create_article_draft",
  title: "Create article draft",
  description: "Create a new draft article authored by the signed-in user. Drafts are not publicly visible.",
  inputSchema: {
    slug: z3.string().trim().min(1).describe("URL slug, lowercase with hyphens."),
    title_fa: z3.string().trim().min(1).describe("Persian title."),
    title_en: z3.string().trim().min(1).describe("English title."),
    summary_fa: z3.string().trim().optional().describe("Short Persian summary."),
    summary_en: z3.string().trim().optional().describe("Short English summary."),
    tags: z3.array(z3.string().trim()).optional().describe("Tag list."),
    categories: z3.array(z3.string().trim()).optional().describe("Category list.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("articles").insert({ ...input, status: "draft", author_id: ctx.getUserId() }).select("id, slug, title_fa, title_en, status").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { article: data }
    };
  }
});

// src/lib/mcp/tools/list-live-sessions.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_live_sessions_default = defineTool4({
  name: "list_live_sessions",
  title: "List live sessions",
  description: "List live/scheduled sessions, newest first, with schedule and status.",
  inputSchema: {
    status: z4.enum(["scheduled", "live", "ended", "cancelled"]).optional().describe("Filter by session status."),
    limit: z4.number().int().min(1).max(50).optional().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("live_sessions").select("id, room_name, title_en, title_fa, description_en, description_fa, status, scheduled_at, started_at, ended_at, max_participants").order("scheduled_at", { ascending: false, nullsFirst: false }).limit(limit ?? 20);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { sessions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/whoami.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
var whoami_default = defineTool5({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in user's profile (name, phone, bio) and roles.",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [{ data: profile }, { data: roles }] = await Promise.all([
      supabase.from("profiles").select("*").eq("user_id", userId).maybeSingle(),
      supabase.from("user_roles").select("role").eq("user_id", userId)
    ]);
    const payload = {
      user_id: userId,
      email: ctx.getUserEmail() ?? null,
      profile: profile ?? null,
      roles: (roles ?? []).map((r) => r.role)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "invdjkxkyytdpervudzw";
var mcp_default = defineMcp({
  name: "kaghaz-o-baad",
  title: "Kaghaz-o-Baad",
  version: "0.1.0",
  instructions: "Tools for Kaghaz-o-Baad, a bilingual (English/Persian) articles and live-sessions platform. Use `list_articles` and `get_article` to read article content and slides, `create_article_draft` to draft a new article as the signed-in user, `list_live_sessions` for upcoming or ongoing sessions, and `whoami` for the current user's profile and roles.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_articles_default, get_article_default, create_article_draft_default, list_live_sessions_default, whoami_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
