// This file is automatically generated / resilient fallback added for preview environments.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL || 'https://invdjkxkyytdpervudzw.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImludmRqa3hreXl0ZHBlcnZ1ZHp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1Mzk5MTUsImV4cCI6MjA3ODExNTkxNX0.0RbeCzLKmgQnTqYhiyP5xSAbGccy37qdcNnUG8z1pqI';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
